services:
  afterpay-tracker:
    build: .
    container_name: afterpay-tracker
    restart: unless-stopped
    ports:
      - "7672:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/data/dev.db
      - AUTH_SECRET=ApgvvKHN9AtM0XeH1fzyZoG3QSPlkUkWGqOaNUCP+aY=
      - NEXTAUTH_SECRET=gUvheYnzYatQEKZnJRLzKHctBckZoDrw16XmNFBU24Q=
      - NEXTAUTH_URL=http://100.99.147.2:7672
      - AUTH_TRUST_HOST=true
    volumes:
      - /volume1/Docker/afterpay-tracker/Data:/data
      - /volume1/Docker/afterpay-tracker/Data/uploads:/app/public/uploads
